"""
backend/report_generator.py
============================
PDF report generator for AquaVeda using fpdf2.
All chart images are generated with matplotlib (no kaleido/plotly export).

Usage
-----
    from backend.report_generator import generate_watershed_report

    pdf_bytes = generate_watershed_report(
        watershed_info=ws_dict,
        change_data=change_dict,
        health_score=health_dict,
        timeseries_data=ts_dict,
        photos_data=photos_list,
    )
    # Pass pdf_bytes to st.download_button(mime="application/pdf")
"""

import os
import datetime
import tempfile

from fpdf import FPDF
from frontend.charts_matplotlib import save_all_report_charts


# ─── brand colours (RGB) ──────────────────────────────────────────────────────
_BLUE       = (30,  136, 229)   # header / accent
_DARK       = (15,   23,  42)   # cover background
_WHITE      = (255, 255, 255)
_LIGHT_GRAY = (241, 245, 249)
_MID_GRAY   = (148, 163, 184)
_TEXT       = (30,   41,  59)
_GREEN      = (26,  152,  80)
_ORANGE     = (245, 110,  67)
_RED        = (215,  48,  39)


# ─── helper: grade -> colour ───────────────────────────────────────────────────
def _grade_color(score: int) -> tuple:
    if score >= 80: return _GREEN
    if score >= 60: return (253, 196,  0)
    if score >= 40: return _ORANGE
    return _RED


# ─── Custom FPDF subclass ─────────────────────────────────────────────────────
class _AquaVedaPDF(FPDF):
    """FPDF2 subclass with branded header/footer and helpers."""

    def __init__(self, watershed_name: str = ""):
        super().__init__(orientation="P", unit="mm", format="A4")
        self._ws_name = watershed_name
        self.set_margins(left=14, top=14, right=14)
        self.set_auto_page_break(auto=True, margin=18)

    # ── Automatic header ──────────────────────────────────────────────────────
    def header(self):
        if self.page_no() == 1:
            return  # Cover page has its own design

        # Blue rule at top
        self.set_fill_color(*_BLUE)
        self.rect(0, 0, 210, 8, "F")

        self.set_y(10)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*_MID_GRAY)
        self.cell(0, 5, f"AquaVeda  |  Watershed Impact Report  |  {self._ws_name}", ln=False, align="L")
        self.cell(0, 5, f"Page {self.page_no()}", ln=True, align="R")
        self.ln(3)

    # ── Text sanitization ─────────────────────────────────────────────────────
    def normalize_text(self, text):
        """Sanitize text to latin-1 to prevent fpdf2 crashes on dynamic data."""
        if not isinstance(text, str):
            text = str(text)
        repl = {
            '\u2013': '-', '\u2014': '-', '\u2018': "'", '\u2019': "'",
            '\u201c': '"', '\u201d': '"', '\u2022': '*', '\u2026': '...',
            '\u2192': '->', '\U0001F30A': '~~ AquaVeda ~~'
        }
        for k, v in repl.items():
            text = text.replace(k, v)
        # Fallback for any other non-latin-1 char (replaced with '?')
        text = text.encode("latin-1", "replace").decode("latin-1")
        return super().normalize_text(text)

    # ── Automatic footer ──────────────────────────────────────────────────────
    def footer(self):
        if self.page_no() == 1:
            return
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*_MID_GRAY)
        self.cell(0, 5,
            "Generated by AquaVeda - Satellite-Based Watershed Monitor  |  SIH 2026",
            align="C")

    # ── Helpers ───────────────────────────────────────────────────────────────
    def section_title(self, text: str):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(*_BLUE)
        self.cell(0, 10, text, ln=True)
        self.set_draw_color(*_BLUE)
        self.set_line_width(0.5)
        self.line(14, self.get_y(), 196, self.get_y())
        self.set_draw_color(0, 0, 0)
        self.set_line_width(0.2)
        self.set_text_color(*_TEXT)
        self.ln(4)

    def kv_row(self, key: str, value: str, highlight: bool = False):
        """Single key-value line with optional colour highlight."""
        if highlight:
            self.set_fill_color(*_LIGHT_GRAY)
            self.set_font("Helvetica", "B", 11)
            self.cell(0, 8, f"  {key}: {value}", fill=True, ln=True)
            self.set_font("Helvetica", "", 11)
        else:
            self.set_font("Helvetica", "", 11)
            self.cell(0, 7, f"  *  {key}: {value}", ln=True)

    def bullet(self, text: str, indent: int = 6):
        self.set_font("Helvetica", "", 11)
        self.set_x(14 + indent)
        self.multi_cell(0, 7, f"*  {text}")

    def table_header(self, cols: list, widths: list):
        self.set_fill_color(*_BLUE)
        self.set_text_color(*_WHITE)
        self.set_font("Helvetica", "B", 10)
        for col, w in zip(cols, widths):
            self.cell(w, 8, col, border=1, fill=True, align="C")
        self.ln()
        self.set_text_color(*_TEXT)

    def table_row(self, values: list, widths: list, shade: bool = False):
        if shade:
            self.set_fill_color(*_LIGHT_GRAY)
        else:
            self.set_fill_color(*_WHITE)
        self.set_font("Helvetica", "", 10)
        for val, w in zip(values, widths):
            self.cell(w, 7, str(val), border=1, fill=True, align="C")
        self.ln()

    def safe_image(self, path, x=None, w=None, h=0):
        """Add image only if path exists and file is non-empty."""
        if path and os.path.exists(path) and os.path.getsize(path) > 0:
            try:
                self.image(path, x=x, w=w, h=h)
                return True
            except Exception as e:
                print(f"[WARN] PDF image insert failed ({path}): {e}")
        return False


# ─────────────────────────────────────────────────────────────────────────────
# PUBLIC API
# ─────────────────────────────────────────────────────────────────────────────

def generate_watershed_report(
    watershed_info: dict,
    change_data: dict,
    health_score: dict,
    timeseries_data: dict,
    photos_data: list,
) -> bytes:
    """Generate a complete watershed impact PDF report.

    Parameters
    ----------
    watershed_info : dict   Watershed metadata (name, state, district, ...)
    change_data    : dict   Output of ``generate_change_summary`` / demo JSON
    health_score   : dict   Output of ``calculate_watershed_health``
    timeseries_data: dict   Keys: ``ndvi_ts``, ``water_ts``
    photos_data    : list   List of field-photo metadata dicts

    Returns
    -------
    bytes  - raw PDF bytes, suitable for ``st.download_button``
    """

    if isinstance(watershed_info, dict) and 'change_data' in watershed_info and change_data == {}:
        data_dict = watershed_info
        watershed_info = data_dict.get('watershed_info', data_dict.get('watershed', {}))
        change_data = data_dict.get('change_data', {})
        health_score = data_dict.get('health_score', {})
        timeseries_data = data_dict.get('timeseries_data', data_dict.get('timeseries', {}))
        photos_data = data_dict.get('photos_data', data_dict.get('photos', []))

    # ── Step 1: generate chart PNGs into a temp directory ────────────────────
    tmp_dir = os.path.join(tempfile.gettempdir(), "aquaveda_report_charts")
    os.makedirs(tmp_dir, exist_ok=True)

    analysis_bundle = {
        "ndvi_ts":      timeseries_data.get("ndvi_ts", []),
        "water_ts":     timeseries_data.get("water_ts", []),
        "health_score": health_score,
        "change_data":  change_data,
        "landuse":      timeseries_data.get("landuse", {}),
        "ws_data":      watershed_info,
    }
    chart_paths = save_all_report_charts(analysis_bundle, temp_dir=tmp_dir + os.sep)

    # ── Step 2: build PDF ─────────────────────────────────────────────────────
    ws_name  = watershed_info.get("name", "-")
    state    = watershed_info.get("state", "-")
    district = watershed_info.get("district", "-")
    start_yr = watershed_info.get("start_year", "-")

    veg     = change_data.get("vegetation", {})
    water   = change_data.get("water", {})
    erosion = change_data.get("erosion", {})

    score = health_score.get("total_score", 0)
    grade = health_score.get("grade", "-")
    recs  = health_score.get("recommendations", [])

    pdf = _AquaVedaPDF(watershed_name=ws_name)

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 1 - COVER
    # ═══════════════════════════════════════════════════════════════════════════
    pdf.add_page()

    # Full-page dark background
    pdf.set_fill_color(*_DARK)
    pdf.rect(0, 0, 210, 297, "F")

    # Top accent bar
    pdf.set_fill_color(*_BLUE)
    pdf.rect(0, 0, 210, 14, "F")

    # Decorative accent rectangle (top-right corner)
    pdf.set_fill_color(20, 80, 150)   # darker blue accent
    pdf.set_draw_color(20, 80, 150)
    pdf.rect(140, 14, 70, 70, "F")

    # Logo emoji (Unicode fallback - just text)
    pdf.set_xy(0, 50)
    pdf.set_font("Helvetica", "B", 56)
    pdf.set_text_color(*_BLUE)
    pdf.cell(0, 20, "~~ AquaVeda ~~", align="C", ln=True)

    # Title
    pdf.set_font("Helvetica", "B", 26)
    pdf.set_text_color(*_WHITE)
    pdf.cell(0, 14, "Watershed Impact", align="C", ln=True)
    pdf.cell(0, 14, "Assessment Report", align="C", ln=True)

    # Divider
    pdf.set_draw_color(*_BLUE)
    pdf.set_line_width(0.8)
    pdf.line(40, pdf.get_y() + 4, 170, pdf.get_y() + 4)
    pdf.set_line_width(0.2)
    pdf.ln(12)

    # Watershed details
    pdf.set_font("Helvetica", "B", 15)
    pdf.set_text_color(*_BLUE)
    pdf.cell(0, 10, ws_name, align="C", ln=True)

    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(*_MID_GRAY)
    pdf.cell(0, 8, f"District: {district}  |  State: {state}", align="C", ln=True)
    pdf.cell(0, 8, f"Analysis Period: {start_yr} - 2024", align="C", ln=True)
    pdf.ln(6)

    # Health score badge
    grade_clr = _grade_color(score)
    pdf.set_fill_color(*grade_clr)
    pdf.set_draw_color(*grade_clr)
    pdf.set_text_color(*_WHITE)
    pdf.set_font("Helvetica", "B", 14)
    badge_x = 75
    pdf.set_x(badge_x)
    pdf.cell(60, 12, f"Health Score: {score}/100  {grade}", fill=True,
             border=0, align="C", ln=True)

    pdf.ln(20)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_MID_GRAY)
    pdf.cell(0, 7,
             "Generated by AquaVeda - Satellite-Based Watershed Monitor",
             align="C", ln=True)
    pdf.cell(0, 7,
             "Data Source: Sentinel-2 (ESA/Copernicus) via Google Earth Engine",
             align="C", ln=True)
    pdf.cell(0, 7,
             f"Report Date: {datetime.date.today().strftime('%B %d, %Y')}",
             align="C", ln=True)

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 2 - EXECUTIVE SUMMARY
    # ═══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("Executive Summary")

    # Health Score callout box
    pdf.set_fill_color(*_LIGHT_GRAY)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, f"  Overall Health Score: {score}/100 - Grade: {grade}",
             fill=True, ln=True)
    pdf.ln(3)

    # Key findings
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*_BLUE)
    pdf.cell(0, 8, "Key Findings:", ln=True)
    pdf.set_text_color(*_TEXT)

    ndvi_bef = veg.get("ndvi_before", 0)
    ndvi_aft = veg.get("ndvi_after", 0)
    nv_ch    = veg.get("change", 0)
    wa_bef   = water.get("area_before_ha", 0)
    wa_aft   = water.get("area_after_ha", 0)
    wa_ch    = water.get("change_percent", 0)
    er_red   = erosion.get("reduction_percent", 0)

    findings = [
        f"Vegetation cover improved by {nv_ch:.2f} NDVI units "
        f"(NDVI: {ndvi_bef:.2f} -> {ndvi_aft:.2f})",
        f"Water body area grew from {wa_bef} ha to {wa_aft} ha (+{wa_ch:.0f}%)",
        f"High erosion risk area reduced by {er_red:.0f}%",
        f"Analysis period: {start_yr} to 2024 "
        f"({2024 - int(start_yr) if str(start_yr).isdigit() else '?'} years of intervention)",
    ]
    for f in findings:
        pdf.bullet(f)
    pdf.ln(4)

    # Sub-scores table
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*_BLUE)
    pdf.cell(0, 8, "Score Breakdown:", ln=True)
    pdf.set_text_color(*_TEXT)

    sub_cols   = ["Component", "Score", "Max", "Grade"]
    sub_widths = [70, 30, 30, 40]
    pdf.table_header(sub_cols, sub_widths)
    rows = [
        ("Vegetation Health",  health_score.get("vegetation_score", 0),  35),
        ("Water Resources",    health_score.get("water_score", 0),        35),
        ("Erosion Control",    health_score.get("erosion_score", 0),      20),
        ("Sustainability",     health_score.get("sustainability_score", 0), 10),
        ("TOTAL",              score,                                     100),
    ]
    for i, (comp, sc, mx) in enumerate(rows):
        g = "A" if sc/mx >= 0.8 else ("B" if sc/mx >= 0.6 else ("C" if sc/mx >= 0.4 else "D"))
        pdf.table_row([comp, sc, mx, g], sub_widths, shade=(i % 2 == 0))
    pdf.ln(5)

    # Health gauge image
    pdf.safe_image(chart_paths.get("health_gauge"), x=50, w=110)

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 3 - VEGETATION ANALYSIS
    # ═══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("Vegetation Analysis")

    # Stats table
    v_cols   = ["Metric", "Before", "After", "Change"]
    v_widths = [70, 38, 38, 38]
    pdf.table_header(v_cols, v_widths)
    veg_rows = [
        ("Mean NDVI",         f"{ndvi_bef:.3f}", f"{ndvi_aft:.3f}", f"+{nv_ch:.3f}"),
        ("Improved Area (ha)", "-",
         f"{veg.get('improved_area_ha', '-')}",
         f"{veg.get('percent_improved', 0):.1f}% of watershed"),
        ("Declined Area (ha)", "-",
         f"{veg.get('declined_area_ha', '-')}", "-"),
    ]
    for i, row in enumerate(veg_rows):
        pdf.table_row(list(row), v_widths, shade=(i % 2 == 0))
    pdf.ln(4)

    # Commentary
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 7,
        f"The NDVI increased by {nv_ch:.2f} units over the project period, representing a "
        f"{(nv_ch / max(ndvi_bef, 0.01) * 100):.0f}% relative improvement in vegetation health. "
        f"Values above 0.4 indicate a healthy, productive landscape."
    )
    pdf.ln(4)

    # NDVI trend chart
    pdf.safe_image(chart_paths.get("ndvi_trend"), x=10, w=186)

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 4 - WATER RESOURCES
    # ═══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("Water Resources Analysis")

    w_cols   = ["Metric", "Before", "After", "Change"]
    w_widths = [70, 38, 38, 38]
    pdf.table_header(w_cols, w_widths)
    wat_rows = [
        ("Water Body Area (ha)",
         str(wa_bef), str(wa_aft),
         f"+{water.get('change_ha', wa_aft - wa_bef):.0f} ha"),
        ("Change Percent", "-", "-", f"+{wa_ch:.0f}%"),
        ("Months with Water/yr",
         str(water.get("months_with_water_before", "-")),
         str(water.get("months_with_water_after", "-")),
         "-"),
    ]
    for i, row in enumerate(wat_rows):
        pdf.table_row(list(row), w_widths, shade=(i % 2 == 0))
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 7,
        f"Water body coverage expanded from {wa_bef} ha to {wa_aft} ha - a "
        f"{wa_ch:.0f}% increase - demonstrating the effectiveness of check dams, "
        f"farm ponds, and percolation structures in improving water retention."
    )
    pdf.ln(4)

    pdf.safe_image(chart_paths.get("water_area"), x=10, w=186)

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 5 - EROSION & LAND USE
    # ═══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("Erosion & Land Use Change")

    # Erosion class table
    e_cols   = ["Risk Class", "Before (ha)", "After (ha)", "Change (ha)"]
    e_widths = [50, 42, 42, 42]
    pdf.table_header(e_cols, e_widths)
    ero_before = erosion.get("classes_before", {})
    ero_after  = erosion.get("classes_after", {})
    for i, cls in enumerate(["Very Low", "Low", "Medium", "High", "Very High"]):
        bv = ero_before.get(cls, 0)
        av = ero_after.get(cls, 0)
        delta = av - bv
        delta_str = f"{delta:+.0f}"
        pdf.table_row([cls, bv, av, delta_str], e_widths, shade=(i % 2 == 0))
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 7,
        f"High and Very High erosion risk areas were reduced by {er_red:.0f}%, "
        f"reflecting improved ground cover and soil conservation measures. "
        f"Contour trenches, gabion structures, and vegetative cover collectively "
        f"contribute to this improvement."
    )
    pdf.ln(4)

    pdf.safe_image(chart_paths.get("erosion_comparison"), x=10, w=186)

    # Land use comparison (if available)
    lu_img = chart_paths.get("landuse_comparison")
    if lu_img:
        pdf.add_page()
        pdf.section_title("Land Use Transition")
        pdf.safe_image(lu_img, x=10, w=186)

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 6 - RECOMMENDATIONS
    # ═══════════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.section_title("Recommendations")

    if recs:
        for i, rec in enumerate(recs, 1):
            # Priority badge
            is_urgent = "urgent" in rec.lower() or "damage" in rec.lower()
            pdf.set_fill_color(*((_ORANGE) if is_urgent else (_BLUE)))
            pdf.set_text_color(*_WHITE)
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(20, 8, f"  {'URGENT' if is_urgent else f'Rec {i}'}", fill=True, border=0)
            pdf.set_text_color(*_TEXT)
            pdf.set_font("Helvetica", "", 11)
            pdf.multi_cell(0, 8, f"  {rec}")
            pdf.ln(2)
    else:
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, "No recommendations generated.", ln=True)

    # ═══════════════════════════════════════════════════════════════════════════
    # PAGE 7 - FIELD VERIFICATION (optional)
    # ═══════════════════════════════════════════════════════════════════════════
    if photos_data:
        pdf.add_page()
        pdf.section_title("Field Verification Log")

        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, f"Total records: {len(photos_data)}", ln=True)
        pdf.ln(3)

        p_cols   = ["Type", "Status", "Latitude", "Longitude", "Date"]
        p_widths = [40, 35, 28, 28, 28]
        pdf.table_header(p_cols, p_widths)

        STATUS_BG = {
            "Functional":   (26, 152,  80),
            "Needs Repair": (245, 158, 11),
            "Damaged":      (215,  48, 39),
            "Dry":          (148, 163,184),
        }

        for i, photo in enumerate(photos_data[:20]):   # cap at 20 rows
            status = photo.get("status", "-")
            bg = STATUS_BG.get(status, (241, 245, 249))
            pdf.set_fill_color(*bg)
            pdf.set_text_color(*((_WHITE) if status in ("Functional", "Damaged") else _TEXT))
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(p_widths[0], 7, photo.get("type", "-")[:18], border=1, fill=True)
            pdf.cell(p_widths[1], 7, status,                        border=1, fill=True, align="C")
            pdf.cell(p_widths[2], 7, f"{photo.get('lat', 0):.4f}",  border=1, fill=True, align="C")
            pdf.cell(p_widths[3], 7, f"{photo.get('lon', 0):.4f}",  border=1, fill=True, align="C")
            pdf.cell(p_widths[4], 7, str(photo.get("date", "-"))[:10], border=1, fill=True, align="C")
            pdf.ln()
            pdf.set_text_color(*_TEXT)

            # Notes sub-row
            notes = photo.get("description", "")
            if notes:
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(*_MID_GRAY)
                pdf.cell(p_widths[0], 5, "", border=0)      # indent
                pdf.multi_cell(0, 5, f"Notes: {notes[:120]}")
                pdf.set_text_color(*_TEXT)

        if len(photos_data) > 20:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(*_MID_GRAY)
            pdf.cell(0, 6, f"... and {len(photos_data) - 20} more records not shown.", ln=True)

    # ── Output ────────────────────────────────────────────────────────────────
    pdf_bytes = bytes(pdf.output())

    # Cleanup temp chart images
    for path in chart_paths.values():
        if path and os.path.exists(path):
            try:
                os.remove(path)
            except OSError:
                pass

    return pdf_bytes


# ── Legacy alias (referenced in old app.py stub) ──────────────────────────────
def generate_pdf_report(watershed_data, charts_paths=None, map_images=None):
    """Legacy stub - delegates to generate_watershed_report for backward compat."""
    ws   = watershed_data.get("ws_data", {})
    cd   = watershed_data.get("change_data", {})
    hs   = watershed_data.get("health_score", {})
    ts   = {k: watershed_data.get(k, []) for k in ("ndvi_ts", "water_ts")}
    ph   = watershed_data.get("photos", [])
    return generate_watershed_report(ws, cd, hs, ts, ph)
